version: "3.1"

services:
  db:
    image: postgres
    container_name: db-delivery
    restart: always
    ports:
      - 5432:5432
    environment:
     POSTGRES_DB: delivery
     POSTGRES_USER:
     POSTGRES_PASSWORD:
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local